# Dataset configuration file

# Dataset Paths
path: data/spark-2022-stream-1
train: train/train
val: val/val

# Number Of Classes
nc: 11

# Class Names
names:
 - cheops
 - debris
 - double_star
 - earth_observation_sat_1
 - lisa_pathfinder
 - proba_2
 - proba_3_csc
 - proba_3_ocs
 - smart_1
 - soho
 - xmm_newton